import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from "react";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import {ThemeProvider} from "@/components/ui/ThemeProvider";
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mursvet | Personal Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
          <link rel="icon" href="/app/icon.png" type="image/x-icon" sizes="32x32"/>
      </Head>
      <body className={inter.className}>
        <Header/>
            {children}
        <Footer/>
      </body>
    </html>
  )
}
